### ISSUE TITLE
s:result_window 'RESULT' requre save do no need

### ISSUE THREAD

**Issue by tsuyoshicho** [skanehira/train.vim#10]
If quit after used, message "save RESULT?" has happen.
It save do no need it.

resolution:
`setlocal buftype=nofile`

---

RESULTのバッファを `setlocal buftype=nofile` するなどして保存不要にするのがよいのではないでしょうか?

**Comment by skanehira** [comment]
`setlocal buftype=nofile` 追加しました
ありがとうざいますっ
