### ISSUE TITLE
コマンドエラーについて

### ISSUE THREAD

**Issue by kato-k** [skanehira/train.vim#11]
こんにちは、train.vimをdeinでインストールさせていただいたのですが、不明なことがあったのでissueを立てさせていただきました。
# 問題
:TrainLateInfo
:TrainSearchRoute
とコマンドを叩くと、
<img width="1442" alt="Screen Shot 0001-06-19 at 6 20 15 PM" src="https://user-images.githubusercontent.com/45391880/59753358-e8e0d100-92be-11e9-9d8a-ab8c697d00e9.png">
のようにエラーが発生します。
# その他
pythonのエラーに見えます
# 予期される挙動
READMEのようにポップアップで結果が表示される。
# バージョン等
macOS Mojave10.14.5
vim 8.1.1517
Python 2.7.16
curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1

issueを出すのが初めてなので不慣れですすいません。失礼します

**Comment by skanehira** [comment]
@kato-k pythonは問題なく動いているんですか？

**Comment by kato-k** [comment]
$ python
(python 2系)コマンドは問題なく起動します

**Comment by kato-k** [comment]
エラーメッセージです
Error detected while processing function train#late_info[1]..<SNR>84_get[6]..<SNR>84_request[33]..16:
line   94:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<string>", line 84, in DummyClassForLocalScope
  File "<string>", line 8, in main
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 69, in <module>
    from array import array
ImportError: dlopen(/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/array.so, 2): Symbol not found: __PySlice_Ad
justIndices
  Referenced from: /usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/array.so
  Expected in: flat namespace
 in /usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/array.so

**Comment by kato-k** [comment]
vimは
+python/dyn
でした

**Comment by skanehira** [comment]
@kato-k おそらく環境が原因かと思われますが、`brew install python@2` で直るそうです
試してみてはどうでしょうか？
https://github.com/anthony-tuininga/cx_Freeze/issues/452

**Comment by kato-k** [comment]
@skanehira HomeBrew で python@2をインストールし直したのですが、状況は変わりませんでした。わざわざ情報を収集してくださってありがとうございます。
ですが、仰るとうりどうもこちらの環境が原因のように感じました。これまで

**Comment by kato-k** [comment]
@skanehira HomeBrew で python@2をインストールし直したのですが、状況は変わりませんでした。ですが、仰るとうりどうもこちらの環境が原因のように感じました。
わざわざ情報を収集してくださってありがとうございます。
原因はよくわからないままですが、自分で調べてみようと思います。
これでissueを閉めます。ありがとうございます。
（投稿の失敗すいません）

**Comment by skanehira** [comment]
@kato-k 
他にも調べた感じいくつか情報がありました
ご参考までにm(_ _)m
https://stackoverflow.com/questions/48897137/import-error-symbol-not-found-pyslice-adjustindices
https://www.oipapio.com/question-22832
https://discuss.pytorch.org/t/resolved-pyslice-adjustindices-error/1475/14
